### ISSUE TITLE
Feature request: pre-commit hook to update codemeta.json

### ISSUE THREAD

**Issue by apirogov** [proycon/codemetapy#38]
It would be great if codemetapy could be used as a pre-commit hook to automatically synchronize e.g. `pyproject.toml` to the `codemeta.json`. 

Currently I have to add it to my dev dependencies and do this:
```yaml
  - repo: local
    hooks:
      - id: codemetapy
        name: codemetapy
        language: system
        entry: poetry run codemetapy -O codemeta.json
        files: ^pyproject.toml$
```

Ideally, I could just point it to this repository any other hook
```yaml
  - repo: https://github.com/proycon/codemetapy
    rev: 'X.Y.Z'
    hooks:
      - id: codemetapy

```
and it should do something "smart" by default :slightly_smiling_face:
